# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches:
      - '*'
      - '!main'  # Exclude main branch
    tags-ignore:
      - '*'  # Ignore tag pushes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio httpx
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest -v
